var fs=require("fs");var XMLTemplateKeyWords=["template","FragmentDefinition"];
function pReaddir(d){"use strict";return new Promise(function(r,a){fs.readdir(d,{withFileTypes:true},function(e,i){r(i);});});}
function pWriteFile(f,d,o){"use strict";return new Promise(function(r,a){fs.writeFile(f,d,o,function(e){if(e){a(e);}else{r();}});});}
function pReadFile(f,o){"use strict";return new Promise(function(r,a){fs.readFile(f,o,function(e,d){if(e){a(e);}else{r(d);}});});}
function getFiles(d){"use strict";return pReaddir(d,{withFileTypes:true}).then(function(i){if(i){var p=[];i.forEach(function(a){if(a.isDirectory()){p=p.concat(getFiles(d+"/"+a.name));}else{p.push(Promise.resolve(d+"/"+a.name));}});return Promise.all(p);}else{return[];}}).then(function(i){var a=[];i.forEach(function(b){a=a.concat(b);});return a;});}
function getLibrariesInDir(d,l){"use strict";var L=d+"/.library";return pReadFile(L,"utf8").then(function(c){c.split("\n").forEach(function(s){var r=s.match("<libraryName>(.*)</libraryName>");if(r!==null){l[r[1]]="";}});});}
function addJsFile(f,c){"use strict";var F=f.replace(/\\/g,"/");if((F.endsWith(".js")||F.endsWith(".ts"))&&F.indexOf("library.js")===-1){var C=F.substring(F.indexOf("src/")+4).replace(/\.[jt]s$/,"");c[C]="";if(F.endsWith(".js")){return pReadFile(F,"utf8").then(function(j){process.stdout.write("Processing JS/TS file :"+f+"\n");var m=j.match(/sap.ui.define\(\s*\[([^\]]*)\]/);if(m){var M=m[1].split(",");M.forEach(function(n){if(n){var a=n.match(/"([^"]*)"/);if(a&&a[1].indexOf(".")<0){process.stdout.write("\tComponent :"+a[1]+"\n");c[a[1]]="";}}});}});}}return null;}
function addFragmentFile(f,F){"use strict";var s=f.replace(/\\/g,"/");if(s.endsWith("fragment.xml")){var a=s.substring(s.indexOf("src/")+4).replace(".fragment.xml","");F.push(a);}}
function getComponentsFromXMLView(f,c){"use strict";if(f.endsWith(".xml")){return pReadFile(f,"utf8").then(function(x){var X=x.split("\n");process.stdout.write("Processing XML file :"+f+"\n");X.forEach(function(l){var m=l.match(/xmlns:{0,1}([a-zA-Z]*)="([a-zA-Z.]*)"/);if(m){var L=m[2];var s=m[1]?m[1]+":":"";X.forEach(function(a){var C=a.match("<"+s+"([A-Z][a-zA-Z.]*)($| |>)");if(C&&XMLTemplateKeyWords.indexOf(C[1])===-1){var b=L.replace(/\./g,"/")+"/"+C[1]+"";process.stdout.write("\tComponent :"+b+"\n");if(b.indexOf("sap/fe/macros/")===0){b+=".metadata";c[b]=L;}else if(b.indexOf("sap/fe")===0){}else{c[b]=L;}}});}});});}else{return Promise.resolve();}}
function main(){"use strict";if(process.argv.length<3){process.stdout.write("missing parameters. Please use --help\n");return;}else if(process.argv[2]==="--help"){process.stdout.write("Usage: getDependencies <dir1> <dir2> ... , where <dirN> is a path to a directory to look for XML views and FE components (javascript files)\n");return;}var d=[],o="./",c={"sap/m/routing/router":"","sap/f/routing/router":"","sap/ui/model/odata/v4/ODataModel":""},l={"sap.fe.templates":""},p=[],f=[];for(var I=2;I<process.argv.length;I++){if(process.argv[I]!=="--out-dir"){d.push(process.argv[I]);}else if(I<process.argv.length-1){I++;o=process.argv[I];}}if(!o.endsWith("/")){o+="/";}d.forEach(function(D){p.push(getLibrariesInDir(D,l));p.push(getFiles(D).then(function(F){var a=[];F.forEach(function(b){a.push(getComponentsFromXMLView(b,c));var j=addJsFile(b,c);if(j){a.push(j);}addFragmentFile(b,f);});return Promise.all(a);}));});Promise.all(p).then(function(){pWriteFile(o+"libraries.json",JSON.stringify(Object.keys(l)),"utf-8");pWriteFile(o+"components.json",JSON.stringify(Object.keys(c)),"utf-8");pWriteFile(o+"fragments.json",JSON.stringify(f),"utf-8");}).catch(function(e){process.stderr.write("Error ("+e.code+"): "+e.message+"\n");});}
main();
